[package]
name = "library"
version = "0.1.0"
edition = "2024"

[lints.clippy]
redundant_closure = "allow"

[features]
denoiser = []

[dependencies]
cgmath = "0.18.0"
log = "0.4.27"
wgpu = "26.0.1"
winit = "0.30.11"
bytemuck = { version = "1.23.1", features = ["derive"] }
pollster = "0.4"
strum = "0.27.2"
strum_macros = "0.27.2"
thiserror = "2.0.12"
palette = "0.7.6"
obj-rs = { version = "0.7.4", features = ["vulkano"] }
anyhow = "1.0.98"
futures-intrusive = "0.5"
futures = "0.3.31"
exr = "1.73.0"
pxm = "0.1.0"
num_enum = "0.7.4"
float-pretty-print = "0.1.1"
derive_more = { version = "2.0.1", features = ["display"] }
disjoint = "0.8.0"
serde_json = "1.0.141"
serde = { version = "1.0.219", features = ["derive"] }
bitflags = "2.9.1"
seahash = "4.1.0"
more-asserts = "0.3.1"
float-cmp = "0.10.0"
etagere = "0.2.15"
cast = "0.3.0"

[dev-dependencies]
tempfile = "3.20.0"
image = "0.25.6"
exr = "1.73.0"
rstest = "0.26.1"
tinytemplate = "1.2.1"
serde = "1.0.219"
test-context="0.4.1"

[build-dependencies]
glob = "0.3.2"
cargo-emit="0.2.1"
