[package]
name = "library"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
log = "0.4.26"
wgpu = "25.0.0"
winit = "0.30.9"
bytemuck = { version = "1.22.0", features = ["derive"] }
pollster = "0.4"
strum = "0.27.1"
strum_macros = "0.27.1"
thiserror = "2.0.12"
palette = "0.7.6"
obj-rs = { version = "0.7.4", features = ["vulkano"] }
anyhow = "1.0.97"
futures-intrusive = "0.5"
futures = "0.3.31"
exr = "1.73.0"
pxm = "0.1.0"

denoiser = { path = "../denoiser" }

[dev-dependencies]
tempfile = "3.19.1"
image = "0.25.6"
exr = "1.73.0"
