[package]
name = "library"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
log = "0.4.26"
wgpu = "24.0.3"
winit = "0.30.9"
bytemuck = { version = "1.22.0", features = ["derive"] }
pollster = "0.4"
strum = "0.27.1"
strum_macros = "0.27.1"
thiserror = "2.0.12"
naga = "24.0.0"
palette = "0.7.6"
obj-rs = "0.7.4"
anyhow = "1.0.97"
tempfile = "3.19.1"