name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:

  build-and-test-at-linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        build-type: [debug, release]

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Install Vulkan Software Implementation
        run: |
          sudo apt update
          sudo apt install -y libvulkan1 mesa-vulkan-drivers

#      Uncomment this in case of local running via 'act'
#      - name: Setup Rust
#        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.build-type }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build (${{ matrix.build-type }})
        run: |
          if [ "${{ matrix.build-type }}" = "release" ]; then
            cargo build --workspace --release --verbose
          else
            cargo build --workspace --verbose
          fi

      - name: Run Tests (${{ matrix.build-type }})
        run: |
          if [ "${{ matrix.build-type }}" = "release" ]; then
            cargo test -p library --release --verbose
          else
            cargo test -p library --verbose
          fi

  build-windows:

    runs-on: windows-latest

    strategy:
      matrix:
        build-type: [ debug, release ]

    steps:

      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.build-type }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build (${{ matrix.build-type }})
        run: |
          if ("${{ matrix.build-type }}" -eq "release") {
          cargo build --workspace --release --verbose
          } else {
          cargo build --workspace --verbose
          }

      - name: Run Tests (${{ matrix.build-type }})
        run: |
          if ("${{ matrix.build-type }}" -eq "release") {
            cargo test -p library --release --verbose
          } else {
            cargo test -p library --verbose
          }