name: Build & Test @ macOS

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:

  build-and-test-at-windows:

    runs-on: macos-latest

    strategy:
      matrix:
        build-type: [ debug, release ]

    steps:

      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Install rustup x86_64 target
        run: rustup target add x86_64-apple-darwin

      - run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.job.os }}

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.build-type }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build (${{ matrix.build-type }})
        run: |
          if [ "${{ matrix.build-type }}" = "release" ]; then
          cargo build --workspace --release --verbose
          else
          cargo build --workspace --verbose
          fi

      - name: Run Tests (${{ matrix.build-type }})
        run: |
          if [ "${{ matrix.build-type }}" = "release" ]; then
            cargo test -p library --release --verbose
          else
            cargo test -p library --verbose
          fi